title: the hallway
description: Random stuff
theme: just-the-docs

url: https://the-hallway.jakereynolds.co

aux_links:
  Github: https://github.com/jacobreynolds
color_scheme: custom

baseurl: /


callouts_level: loud # or loud
callouts:
  note-title:
    color: grey-lt
    title: A note from the editor


compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true